services:
  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: agent_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  ollama:
    image: ollama/ollama:0.18.1
    ports:
      - ":11434"
    entrypoint: >
      sh -c "ollama serve"
    environment:
      OLLAMA_NUM_THREADS: 8
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434 || exit 1'"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - ollama-data:/root/.ollama
    runtime: nvidia
    
  memory_server:
    build:
      context: .
      dockerfile: server/memory/Dockerfile
    container_name: memory_server
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      DB_SERVICE: "database"
    ports:
      - "${MEMORY_SERVER_PORT}:8003"
    depends_on:
      - ollama
      - database

  agent:
    build: 
      context: .
      dockerfile: graph/Dockerfile
    container_name: agent
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      DB_SERVICE: "database"
      MEMORY_SERVER_SERVICE: "memory_server"
    ports:
      - "${AGENT_PORT}:8002"
    depends_on:
      - ollama
      - memory_server

volumes:
  pgdata:
  ollama-data: